### ISSUE TITLE
Create supporting repositories

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-project#1]
* Relaton Python (should support conversion to BibTeX and CSL output in the future) (@yablokov, @CAMOBAP and @andrew2net )
  * Parsers for:
    * bibxml-w3c
    * bibxml-3gpp
    * bibxml-ieee
    * bibxml-doi
    * bibxml-iana
    * bibxml-nist
    * bibxml-ietf (to link with bibxml-rfcs, bibxml-ids, and bibxml-rfcsubseries)
* Django BibXML, includes access to datastore, public/private APIs, authentication (@yablokov @strogonoff )
* Docker/k8n configuration (@yablokov ?)
* Reimplementation of `doilit` in Python => [doi2ietf-py](https://github.com/ietf-ribose/doi2ietf-py) (@yablokov )

**Comment by ronaldtse** [comment]
When we need testing infrastructure @phuonghuynh and @kwkwan will assist.

**Comment by CAMOBAP** [comment]
@ronaldtse as far as I understand those parsers must be in separate repositories.

Also as far as I understood original ruby repos for those parsers are https://github.com/relaton/relaton-*, can you confirm this?

If my assumption is right I can start with https://github.com/relaton/relaton-bib as dependency for all those parsers

**Comment by ronaldtse** [comment]
> I can start with https://github.com/relaton/relaton-bib as dependency for all those parsers

Right.

I don't actually think we need all these parsers in the Python flavor because we can reuse the Relaton Ruby code. 

* The only ones that need Python are the "dynamically fetched" ones, i.e. bibxml-doi, bibxml-iana, bibxml-ietf.
* For w3c, 3gpp, ieee, nist, we can use Relaton Ruby to run in GHA, and create the BibXML files in the necessary repositories.

We will need to make GitHub repositories for each of these datasets (details here: https://www7.ietf.org/media/documents/BibXML_Service_RFP.pdf):

* bibxml-rfcs (bibxml)
* bibxml-misc (bibxml2)
* bibxml-ids (bibxml3)
* bibxml-w3c (bibxml4)
* bibxml-3gpp (bibxml5)
* bibxml-ieee (bibxml6)
* bibxml-doi (bibxml7)
* bibxml-iana (bibxml8)
* bibxml-rfcsubseries (bibxml9)
* bibxml-nist

**Comment by CAMOBAP** [comment]
@ronaldtse To be on the same page can I use https://github.com/ietf-ribose/bibxml-project repository for converted https://github.com/relaton/relaton-bib code?

**Comment by ronaldtse** [comment]
Use Relaton/Relaton-py repo please.

**Comment by ronaldtse** [comment]
Or relaton/Relaton-bib-py. 

That repository was meant only to host the README.

**Comment by strogonoff** [comment]
Django project, along with the accompanying Dockerfile and compose configuration, resides in https://github.com/ietf-ribose/bibxml-service.

**Comment by ronaldtse** [comment]
bibxml-data-iana can now be a static one.

**Comment by ronaldtse** [comment]
All repositories created, closing this.
