### ISSUE TITLE
BibXML data sources

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-project#10]
BibXML service & indexer has generic support for datasets indexing & retrieval, including legacy paths.

However, the only working dataset in reality is NIST, since `bibxml-data-` sources are missing for almost all other datasets. BibXML data sources are not in scope of service & indexer Django projects per se, and I don’t know where those issues are tracked. ping @ronaldtse 

For a couple of datasets that do have BibXML data, they don’t have Relaton data (https://github.com/ietf-ribose/bibxml-indexer/issues/12, https://github.com/ietf-ribose/bibxml-indexer/issues/7) but we can probably do conversion in Python soon (https://github.com/ietf-ribose/bibxml-indexer/issues/25).

**Comment by ronaldtse** [comment]
@strogonoff these datasets exist:

* https://github.com/ietf-ribose/bibxml-data-ieee
* https://github.com/ietf-ribose/bibxml-data-w3c

**Comment by ronaldtse** [comment]
The full list of sources tracked is this: https://github.com/ietf-ribose/bibxml-service/issues/8

The project to track is this: https://github.com/orgs/ietf-ribose/projects/3/views/1

**Comment by strogonoff** [comment]
> these datasets exist:

@ronaldtse yes, this is acknowledged in my ticket. For them we still don’t have Relaton data.

**Comment by strogonoff** [comment]
Closing as a dupe of #3.
