### ISSUE TITLE
Feature request: ability to specify anchor returned via /public/rfc URLs

### ISSUE THREAD

**Issue by rjsparks** [ietf-ribose/bibxml-project#24]
This is an xml2rfc.tools.ietf.org behavior that we missed, and a few things are using it.

Note that https://xml2rfc.tools.ietf.org/public/rfc/bibxml-doi/reference.DOI.10.1145/2975159.xml?anchor=JUPITER returns bibxml with the anchor set to "JUPITER". 

How difficult would it be to add that behavior to the current bibxml implementation?

**Comment by ronaldtse** [comment]
@rjsparks sorry for the delay here (probably should go into the bibxml-service repo), I missed this.

I believe we already support specifying a custom anchor, but not sure about in DOI. Ping @strogonoff .

**Comment by strogonoff** [comment]
1. This is supported for all API endpoints that return XML, if not this must be a bug! Anchor parameter is documented here: https://bib.ietf.org/api/v1/#operation/getBibItemByDocId
2. But, this appears to not work for xml2rfc paths.

**Comment by ronaldtse** [comment]
Closing in favor of and carrying over to https://github.com/ietf-tools/bibxml-service/issues/276
