### ISSUE TITLE
Implement `bibxml-data-*`

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-project#3]
Implement bibxml-data-*:
* bibxml-rfcs (bibxml)
* bibxml-misc (bibxml2)
* bibxml-ids (bibxml3)
* bibxml-w3c (bibxml4)
* bibxml-3gpp (bibxml5)
* bibxml-ieee (bibxml6)
* bibxml-iana (bibxml8)
* bibxml-rfcsubseries (bibxml9)
* bibxml-nist

Implement dynamic bibxml fetch:
* bibxml-doi (bibxml7)

**Comment by ronaldtse** [comment]
@strogonoff https://github.com/ietf-ribose/relaton-data-ieee/ is now ready.

**Comment by strogonoff** [comment]
Relaton data sources were switched to `ietf-ribose` org. (We still miss sources for IETF authoritative datasets and some others.)

**Comment by strogonoff** [comment]
By the way, dynamic fetch is probably not in the scope of this ticket, `bibxml-service` handles that.

**Comment by andrew2net** [comment]
@ronaldtse  these are done:

> Implement bibxml-data-*:
> 
> * bibxml-rfcs (bibxml)
> * bibxml-misc (bibxml2)
> * bibxml-ids (bibxml3)
> * bibxml-w3c (bibxml4)
> * bibxml-3gpp (bibxml5)
> * bibxml-ieee (bibxml6)
> * bibxml-iana (bibxml8)
> * bibxml-rfcsubseries (bibxml9)
> * bibxml-nist

What are the requirements for the bibxml-doi?

> Implement dynamic bibxml fetch:
> 
> * bibxml-doi (bibxml7)

**Comment by ronaldtse** [comment]
@andrew2net bibxml-doi is a conversion of DOI to BibXML format. There is no dataset because the DOI dataset is too large and cannot be retrieved. This part is implemented in Python, so we don't require the Ruby, but for Relaton itself we need to have a relaton-doi gem that can retrieve DOI information, and also produce a mapping for the Crossref/DOI data structure to Relaton.

**Comment by andrew2net** [comment]
@ronaldtse then I'll open a new issue in the Relaton. I'm unable to close this issue. Can you?

**Comment by ronaldtse** [comment]
Closed. Thanks!

**Comment by ronaldtse** [comment]
Relaton-DOI here: https://github.com/relaton/relaton-doi/issues/1
