### ISSUE TITLE
“Canonical” dataset ID (question)

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-project#4]
Among these datasets (https://github.com/ietf-ribose/bibxml-service/issues/10#issue-1027036948), which style should be be considered the “authoritative” dataset ID? 

```bibxml```, ```bibxml3```, ```bibxml5```, etc.

or

```IETF RFC```, ```IETF I-D```, ```3GPP```, etc.

ping @ronaldtse (can’t assign issues in this repository)

**Comment by strogonoff** [comment]
Dataset ID will be based on this pattern for now: `https://github.com/ietf-ribose/bibxml-data-{dataset ID}`.

**Comment by ronaldtse** [comment]
For the "authoritative" dataset IDs, let's use these:

* `rfcs` (bibxml)
* `ids` (bibxml3)
* `rfcsubseries` (bibxml9)
* `misc` (bibxml2)
* `w3c` (bibxml4)
* `3gpp` (bibxml5)
* `ieee` (bibxml6)
* `iana` (bibxml8)
* `doi` (bibxml7)
* `nist` (no existing id)

UPDATED: 20211117: doi is bibxml7 not bibxml9.

**Comment by strogonoff** [comment]
@ronaldtse OK. Note, indexer service will rely on those dataset IDs for default source repo patterns (`/ietf-ribose/bibxml-data-{id}`, `/relaton/relaton-data-{id}`). (It will provide a way to override per-dataset source in project settings in case URLs or branch names change, pushing a refactor that accommodates this.)

**Comment by strogonoff** [comment]
For the record, I found additional dataset IDs in previously existing OpenAPI spec—removing these from the spec and replacing with IDs provided above until something changes later:

- ecma
- itu-r
- calconnect
- cie
- iso
- bipm

**Comment by strogonoff** [comment]
https://github.com/ietf-ribose/bibxml-indexer/commit/92f9ce0cff991deabffa24209b4c39198c403c4b

**Comment by ronaldtse** [comment]
Sorry @strogonoff my mistake -- DOI is bibxml7 not bibxml9.
