### ISSUE TITLE
Missing legacy paths <-> `bibxml-data-` mappings

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-project#5]
- This legacy entry:

  http://xml2rfc.tools.ietf.org/public/rfc/bibxml6/reference.IEEE.ISO_IEC_26702_IEEE_STD_1220_2005_FIRST_EDITION_2007_07_15.xml

  Does not match the entry we have in `bibxml-data-ieee`: [ISO_IEC_26702.xml](https://github.com/ietf-ribose/bibxml-data-ieee/blob/main/data/ISO_IEC_26702.xml). Our entry seems like a newer version.

- Meanwhile, this same [ISO_IEC_26702.xml](https://github.com/ietf-ribose/bibxml-data-ieee/blob/main/data/ISO_IEC_26702.xml) that we have does not exist in legacy data under `/public/rfc/bibxml6/` (there’s no other 26702 there).

- As another example, this document in `bibxml-data-` does not seem to appear in _any_ legacy dataset (and definitely not in `bibxml6`):

  https://github.com/ietf-ribose/bibxml-data-ieee/blob/main/data/ANSI_N42-33.2019.xml

  Also, it’s ANSI but is somehow in bibxml-data-ieee dataset. Is this intended or an error?

cc @ronaldtse  @andrew2net

**Comment by strogonoff** [comment]
I have been operating under these assumptions:

- legacy paths contain at least a subset (or all) of the data that we have under `bibxml-data-`,
- we build `bibxml-data-` by processing /public/rfc/ data for the time being.

Are these assumptions correct?

If not, is `bibxml-indexer` supposed to scrape legacy /public/rfc/ paths, and cannot rely on `bibxml-data-` as exhaustive data source after all?

**Comment by ronaldtse** [comment]
The "non-IEEE" identifiers in the IEEE dataset are one of two types:

1. Documents with multiple identifiers. 
  - They should only use the IEEE designation or the joint one (in the case they don't have an IEEE-specific identifier)
2. Non-IEEE documents.
  - They should use whatever identifier that is available, because it is difficult to ascertain their correctness in bulk. 

Note that out of around 9900 IEEE documents we are only successful in parsing around 9000 - there are a few hundred anomalies. 

(@andrew2net can you confirm this is correct and documented?)

**Comment by ronaldtse** [comment]
> - legacy paths contain at least a subset (or all) of the data that we have under `bibxml-data-`,

Legacy paths contain a subset of data available under `bibxml-data-`. 

For the cases of IETF authoritative data (RFC, IDs, rfcsubseries), and "misc", the datasets should be identical. 

For the rest, the legacy datasets are a subset. 

> - we build `bibxml-data-` by processing /public/rfc/ data for the time being.

No, all datasets are built from their authoritative sources. Only the "misc" dataset is sourced from the legacy dataset. 

> If not, is `bibxml-indexer` supposed to scrape legacy /public/rfc/ paths, and cannot rely on `bibxml-data-` as exhaustive data source after all?

No. `bibxml-indexer` must ONLY source from the `bibxml-data-` datasets.

We only want to support the "legacy paths", not the legacy datasets. Please IGNORE the legacy datasets.

**Comment by ronaldtse** [comment]
> Also, it’s ANSI but is somehow in bibxml-data-ieee dataset. Is this intended or an error?

So for some reason, IEEE's dataset does contain some non-IEEE standards. It's... complicated. 
- some are from legacy organizations, eg. predecessor to the IEEE's name (was AIE), organizations subsumed by IEEE
- some are joint development standards, eg. IEEE/ISO/IEC, IEEE/CIE, IEEE/ANSI
- some are IEEE developed "for" another organization. 

This particular example is the last case - a standard developed by IEEE for ANSI and does not have an IEEE standard identifier. 

You can see it at the corresponding IEEE page: https://ieeexplore.ieee.org/document/8863802

**Comment by andrew2net** [comment]
> (@andrew2net can you confirm this is correct and documented?)

It's correct. The converter generates a report with IDs it's unable to parse, duplications, and unresolved relations.

**Comment by strogonoff** [comment]
Where do reports get stored?

In https://github.com/ietf-ribose/bibxml-data-ieee/ for example I see only a date in flag.txt, does this mean there was nothing report, or report is not versioned in Git?

**Comment by andrew2net** [comment]
> Where do reports get stored?

@strogonoff it isn't stored in the repo. It's generated as an output of the command `relaton fetch-data ieee-rawbib` (see the [doc](https://github.com/relaton/relaton-cli#relaton-fetch-data). You can see last repor [here](https://github.com/ietf-ribose/bibxml-data-ieee/runs/4226615151?check_suite_focus=true)
