### ISSUE TITLE
Routing legacy dataset that has multiple matches in `bibxml-data-`

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-project#6]
Based on @ronaldtse’s comment at https://github.com/ietf-ribose/bibxml-project/issues/4#issuecomment-970312922, we have a single legacy dataset mapping to multiple “new” datasets:

> * `rfcsubseries` (bibxml9)
> * `doi` (bibxml9)

Do we implement routing with fallback? Say, we get a request to `/public/rfc/bibxml9/reference.REF_ID.xml`. We configure the service map `bibxml9` to a list `['rfcsubseries', 'doi']`. It first tries that exact REF_ID in `rfcsubseries`, and if there’s no match then it tries `doi`. Does that logic make sense from IETF’s standpoint?

**Comment by ronaldtse** [comment]
Wait, http://xml2rfc.tools.ietf.org/public/rfc/bibxml9/ is only rfcsubseries. My mistake. `bibxml-doi` is bibxml7.
