### ISSUE TITLE
File naming in `bibxml-data-` repositories (question)

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-project#8]
What logic is used for naming the files within `bibxml-data-` repos? I want to know, for files under `data/`, where the part of the filename before the extension comes from, and what special significance it has (if any).

**Comment by ronaldtse** [comment]
* Each of the files are named according to the publishers' "document identifier" scheme. e.g. NIST documents use NIST's PubID.
* However, many SDOs do not have a consistent document ID. In those cases, Relaton provides a consistent ID scheme for them. @andrew2net can elaborate on the patterns of each.
* The IDs are not important for retrieval - the bibxml-indexer should just import all the files and the contents of the `bibxml-data-` files.

**Comment by strogonoff** [comment]
Services need a “canonical reference” (citation ID unique within a dataset) for use in URLs like `/api/v1/ref/<DATASET>/<REF>/`, `/public/rfc/<LEGACY DATASET>/reference.<REF>.xml` and others.

Currently services use `bibxml-data-` filenames as such canonical references.

If filenames right now don’t carry significance, should we make filenames in `bibxml-data-` reflect canonical references we want to use, for consistency?

**Comment by ronaldtse** [comment]
> The IDs are not important for retrieval

The IDs are important for identification, but they are "not important" for retrieval -- because there are multiple ways of retrieving the same bibliographic information (e.g. legacy path, by partial ID or some filtering mechanism).

In the case of a "canonical reference", we should promote the use of the defined IDs (i.e. the filenames).

**Comment by strogonoff** [comment]
OK, we use filenames as references currently, and it seems no change is needed.

If we want to use different references in URLs—for example, if we want `/public/rfc/bibxml-nist/reference.NIST.TN.2160.xml` to work instead of current `/public/rfc/bibxml-nist/reference.NIST_TN_2160.xml`, or something like that—I suggest to adjust `bibxml-data-` GHA build implementation (this will affect final URLs, but we can do it since it’s not production yet).
